### ISSUE TITLE
Failed to create table columbus.shp in DuckDB

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/reactgeoda#187]
Error: {"exception_type":"Not implemented","exception_message":"Failed to create table 'columbus.shp': Arrow Type with extension name: geoarrow.polygon and format: +l, is not currently supported in DuckDB."}
    at ma.insertArrowFromIPCStream (duckdb-browser-eh.worker.2b5d1fe1.js:1:756696)
    at Fo.onMessage (duckdb-browser-eh.worker.2b5d1fe1.js:1:744116)
    at Wc.globalThis.onmessage (duckdb-browser-eh.worker.2b5d1fe1.js:1:776842)

**Comment by lixun910** [comment]
See [Fix] import geoarrow into duckdb failed #194

**Comment by lixun910** [comment]
Notes:

1.  The current DuckDB WASM module doesn't support the geoarrow ARROW:extension See: https://github.com/duckdb/duckdb/blob/7f34190f3f94fc1b1575af829a9a0ccead87dc99/src/function/table/arrow.cpp#L118, so we have to update arrowTable and change the fields in schema temporarily that if metadata has key 'ARROW:extension:name' and value starts with 'geoarrow'

2. The DuckDB WASM can load spatial extension "duckdb spatial", which takes about 5.8MB compressed size to load. While it is not as efficient as geoarrow, we can still take advantage of this extension to expose spatial operations like ST_BUFFER, ST_INTERSECT to the frontend. We can do e.g. converting the geoarrow column to "GEOMETRIC" column (stored as wkb).
